### ISSUE TITLE
Design suggestions and Mobile issues

### ISSUE THREAD

**Issue by PalmaAnd** [MaximilianMauroner/home#1]
@MaximilianMauroner 
- [x] "Projects" - page, reduce zoom, as right now I get lost when I hover over the image
- [x] "Who am I" - page: Maybe change background or color animation as the text is sometimes hard to read
- [x] Fix known issues on mobile

**Comment by PalmaAnd** [comment]
- [x] "Who am I" - page: Clicking on "This Website" opens a new tab with the same page, is this wanted?
- [x] "Who am I" - page: Audible Highlights Transcriber and Personal Notion Manager have the same link

**Comment by MaximilianMauroner** [comment]
should all be resolved with #6 and #7
